# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: rikorose/gcc-cmake:latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          # https://fossies.org/linux/ldc/.circleci/config.yml
          name: Install prerequisites
          command: |
            apt-get -q update
            # https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages
            apt-get -yq install ninja-build
      - checkout
      - run: g++ --version
      - run: cmake --version
      - run:
          name: Build
          command: |
            cmake -G Ninja -S . -B ./build


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test-workflow:
    jobs:
      - build
